### ISSUE TITLE
In wiki add namespace to all identifiers

### ISSUE THREAD

**Issue by EmmanuelMess** [jeremydumais/CPP-DateTime-library#2]
Like this:

    jed_utils::datetime dtTest = jed_utils::datetime();

**Comment by jeremydumais** [comment]
Hi Emmanuel,

Very sorry for the delay I completely forgot this documentation issue.
Here is what will be added to the wiki page:

### Don't forget the namespace

Note: To simplify the example code below, we will assume that you have use the
jed_utils namespace in the source file like this:

```c++
use namespace jed_utils;
```

Otherwise if you prefer, you will have to specify the namespace on each class
of the library like this :

```c++
jed_utils::datetime dtTest = jed_utils::datetime();
```

Thank you,
